version: '3.7'

services:
  mariadb:
    image: mariadb:10.11.7
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb-data:/lib/var/mysql
      - ../common/initdb.d:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${USER_NAME}
      MARIADB_PASSWORD: ${USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
  auth-mariadb:
    image: mariadb:10.11.7
    container_name: auth-mariadb
    restart: unless-stopped
    volumes:
      - auth-mariadb-data:/lib/var/mysql
      - ../auth/initdb.d:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_DATABASE: ${AUTH_DB_NAME}
      MARIADB_USER: ${AUTH_USER_NAME}
      MARIADB_PASSWORD: ${AUTH_USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD}
      TZ: 'Asia/Seoul'
    ports:
      - "3307:3306"
  auth-radis:
    image: redis:7.2.4
    container_name: auth-radis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${AUTH_REDIS_PASSWORD}
    volumes:
      - auth-redis-data:/data
    ports:
      - "6379:6379"

  user-mariadb:
    image: mariadb:10.11.7
    container_name: user-mariadb
    restart: unless-stopped
    volumes:
      - user-mariadb-data:/lib/var/mysql
      - ../user/initdb.d:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_DATABASE: ${USER_DB_NAME}
      MARIADB_USER: ${USER_USER_NAME}
      MARIADB_PASSWORD: ${USER_USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${USER_DB_ROOT_PASSWORD}
      TZ: 'Asia/Seoul'
    ports:
      - "3308:3306"

  place-neo4j:
    image: neo4j:5.19.0-community
    container_name: place-neo4j
    restart: unless-stopped
    volumes:
      - place-neo4j-data:/data
    environment:
      TZ: 'Asia/Seoul'
    ports:
      - "7474:7474"
      - "7687:7687"

  tour-neo4j:
    image: neo4j:5.19.0-community
    container_name: tour-neo4j
    restart: unless-stopped
    volumes:
      - tour-neo4j-data:/data
    environment:
      NEO4J_AUTH: ${TOUR_NEO4J_USER_NAME}/${TOUR_NEO4J_USER_PASSWORD}
      TZ: 'Asia/Seoul'
    ports:
      - "7475:7474"
      - "7688:7687"

  checklist-neo4j:
    image: neo4j:5.19.0-community
    container_name: checklist-neo4j
    restart: unless-stopped
    volumes:
      - checklist-neo4j-data:/data
    environment:
      TZ: 'Asia/Seoul'
    ports:
      - "7476:7474"
      - "7689:7687"

  payment-mongodb:
    image: mongo:7.0
    container_name: payment-mongodb
    restart: unless-stopped
    volumes:
      - payment-mongodb-data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PAYMENT_MONGO_DB_ROOT_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PAYMENT_MONGO_DB_ROOT_USER_PASSWORD}
      DB_NAME: ${PAYMENT_MONGO_DB_NAME}
    ports:
      - "27017:27017"

  payment-mongo-express:
    image: mongo-express
    container_name: payment-mongo-express
    restart: unless-stopped
    ports:
      - "8888:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${PAYMENT_MONGO_DB_ROOT_USER_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${PAYMENT_MONGO_DB_ROOT_USER_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: payment-mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${PAYMENT_MONGO_EXPRESS_USER_NAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${PAYMENT_MONGO_EXPRESS_USER_PASSWORD}

volumes:
  mariadb-data:
  auth-redis-data:
  auth-mariadb-data:
  user-mariadb-data:
  place-neo4j-data:
  tour-neo4j-data:
  checklist-neo4j-data:
  payment-mongodb-data:

networks:
  default:
    external: true
    name: TourlistNetwork