apiVersion: v1
kind: Service
metadata:
  name: tourlist-auth-service
spec:
  type: ClusterIP
  selector:
    app: tourlist-auth-pod
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourlist-auth-deployment
  labels:
    app: tourlist-auth-pod
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tourlist-auth-pod
  template:
    metadata:
      labels:
        app: tourlist-auth-pod
    spec:
      containers:
        - name: tourlist-auth
          image: ssuyas/tourlist_auth
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: tourlist-auth-config
            - secretRef:
                name: tourlist-auth-secrets

