apiVersion: v1
kind: Service
metadata:
  name: tourlist-user-service
spec:
  type: ClusterIP
  selector:
    app: tourlist-user-pod
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourlist-user-deployment
  labels:
    app: tourlist-user-pod
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tourlist-user-pod
  template:
    metadata:
      labels:
        app: tourlist-user-pod
    spec:
      containers:
        - name: tourlist-user
          image: ssuyas/tourlist_user:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: tourlist-user-config
            - secretRef:
                name: tourlist-user-secrets

